# Generated by Django 5.1.7 on 2025-03-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_alter_item_text_alter_item_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
    ]
